# -*- coding: utf-8 -*-
"""
/***************************************************************************
 INDE
                                 A QGIS plugin
 This plugin allows connection to all ows services available in Brazil National Spatial Data Infrastructure
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-10-26
        copyright            : (C) 2020 by Julierme G Pinheiro / Censipam - Ministry of Defense
        email                : julierme.pinheiro@sipam.gov.br
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load INDE class from file INDE.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .INDE import INDE
    return INDE(iface)
